window:
  padding:
    x: 8
    y: 8
  opacity:  0.90
 
font:
  normal:
    family: "Fira Code"
    style: Medium
  bold:
    family: "Fira Code"
    style: Bold
  italic:
    family: "Fira Code"
    style: Italic
  bold_italic:
    family: "Fira Code"
    style: Bold Italic
  size: 14.0
 
 
colors:
 
  primary:
    #background: '0x0b0b0b'
     background: '0x000000'
     foreground: '0xC6C6C4'
 
  normal:
    black:   '0x666666'
    red:     '0xeb606b'
    green:   '0xc3e88d'
    yellow:  '0xf7eb95'
    blue:    '0x80cbc4'
    magenta: '0xff2f90'
    cyan:    '0xaeddff'
    white:   '0xffffff'
 
 
  bright:
    black:   '0xff262b'
    red:     '0xeb606b'
    green:   '0xc3e88d'
    yellow:  '0xf7eb95'
    blue:    '0x7dc6bf'
    magenta: '0x6c71c4'
    cyan:    '0x35434d'
    white:   '0xffffff'

       #   bright:
       #     black: '#323437'
       #     red: '#ff5454'
       #     green: '#8cc85f'
       #     yellow: '#e3c78a'
       #     blue: '#80a0ff'
       #     magenta: '#d183e8'
       #     cyan: '#79dac8'
       #     white: '#a1aab8'
       # 
       #   normal:
       #     black: '#7c8f8f'
       #     red: '#ff5189'
       #     green: '#36c692'
       #     yellow: '#bfbf97'
       #     blue: '#74b2ff'
       #     magenta: '#ae81ff'
       #     cyan: '#85dc85'
       #     white: '#e2637f'

